// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
 import 'firebase_options.dart';

 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3pWqwiTMGt_7C2vNAMtyRmAf-cOUWCc',
    appId: '1:729488646624:ios:593a2ba5655271d719cb85',
    messagingSenderId: '729488646624',
    projectId: 'all-n-do',
    storageBucket: 'all-n-do.appspot.com',
    iosBundleId: 'com.example.allndo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwBRZ9UchtzfwoHyCULEmjxkY7JuGAZl4',
    appId: '1:729488646624:web:c5ea101838ae678419cb85',
    messagingSenderId: '729488646624',
    projectId: 'all-n-do',
    authDomain: 'all-n-do.firebaseapp.com',
    storageBucket: 'all-n-do.appspot.com',
    measurementId: 'G-FRD5C91E61',
  );
}
